// <auto-generated/>
using System.Diagnostics.CodeAnalysis;

// Mainly used for PrettyConsoleInterpolatedStringHandler (will be used at call site by the compiler)
[assembly: SuppressMessage(
	"Style",
	"IDE0060:Remove unused parameter",
	Justification = "Parameters may be intentionally unused for API shape consistency or interface compliance.")]