# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: Multi-Platform Tests

on:
  push:
    branches: [ "Future" ]
  pull_request:
    branches: [ "Future" ]
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Corrected comma separation
        configuration: [Debug, Release]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Conditionally add MSBuild to the PATH only on Windows
    - name: Setup MSBuild.exe
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}
      env:
        Solution_Name: ${{ secrets.SOLUTION_NAME }}  # Ensure this secret is defined
        Configuration: ${{ matrix.configuration }}

    # Decode the base64 encoded pfx and save the Signing_Certificate
    - name: Decode the pfx
      shell: pwsh
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path "${{ secrets.WAP_PROJECT_DIRECTORY }}" -ChildPath "GitHubActionsWorkflow.pfx"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
      env:
        Wap_Project_Directory: ${{ secrets.WAP_PROJECT_DIRECTORY }}

    # Remove the pfx
    - name: Remove the pfx
      shell: pwsh
      run: |
        if ($env:RUNNER_OS -eq 'Windows') {
          Remove-Item -Path "${{ secrets.WAP_PROJECT_DIRECTORY }}\GitHubActionsWorkflow.pfx"
        } else {
          Remove-Item -Path "${{ secrets.WAP_PROJECT_DIRECTORY }}/GitHubActionsWorkflow.pfx"
        }
      env:
        Wap_Project_Directory: ${{ secrets.WAP_PROJECT_DIRECTORY }}
